service: laravel-app

provider:
    name: aws
    region: ap-southeast-1
    stage: production
    ecr:
        images:
            laravel-image:
                path: ./

functions:
    web:
        image:
            name: laravel-image
        events:
            -   httpApi: '*'
        logRetentionInDays: 7
