name: Laravel Lambda Container

on:
  push:
    branches: [ development, staging, production]
  pull_request:
    branches: [ development, staging, production]

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
          
      - name: Node 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
      
      - name: Install Serverless Framework
        run: npm install -g serverless
      
      - name: Install depedencies
        uses: php-actions/composer@v6
      
      - name: PHP artisan
        run: php artisan key:generate && php artisan cache:clear
        
      - name: Deploy using Serverless Framework
        run: serverless deploy
